### PR TITLE
Improve the configuration.

### PR DESCRIPTION
**Pull request by hsorby**
Fix up some issues with configuring libCellML.

Addresses issue #254.

### CODE REVIEW

**Review by nickerso — COMMENTED** [review]
Need to actually test that this works as expected, but looks like it will address #254

**Comment by MichaelClerx** [comment]
@nickerso what's the status of this PR?

**Comment by nickerso** [comment]
The changes look good to me, but I still haven't actually tested it. If someone else can confirm things actually work as expected now, we should merge it in.

**Review by agarny — APPROVED** [review]
I have just tested this PR using
```
cd [libCellML] && mkdir build && cd build && ccmake -DLIBCELLML_BINDINGS_PYTHON=OFF -DLIBCELLML_BUILD_SHARED=OFF -DLIBCELLML_BUILD_TYPE=Release -DLIBCELLML_COVERAGE=OFF -DLIBCELLML_INSTALL_PREFIX=/my/path -DLIBCELLML_TREAT_WARNINGS_AS_ERRORS=OFF -DLIBCELLML_UNIT_TESTS=OFF ..
```

and everything was set as expected. So, good to go for me.

**Pull request merged**
