### PR TITLE
Segfault in flatten

### PR DESCRIPTION
**Pull request by kerimoyle**
Test to show segfault in the flatten method, demonstrates #517

### CODE REVIEW

**Comment by hsorby** [comment]
Problem solved and the code is ready for review.  But Mac is offline.

**Comment by hsorby** [comment]
Ready for review. I guess @kerimoyle  and I can work as one on this?

**Review by kerimoyle — COMMENTED** [review]
Looks good to me! Happy for @hsorby to approve as I can't :)

**Review by hsorby — APPROVED** [review]
@kerimoyle and I think this is good to go.

**Review by agarny — APPROVED** [review]

**Pull request merged**
