### PR TITLE
Remove validation from parser

### PR DESCRIPTION
**Pull request by kerimoyle**
- Removed checks for names of variables and units from `Parser::ParserImpl::loadVariable` function - they are checked in the validator.
- Updated Parser tests to match above.
Commented out only at the moment.

Addresses issue #302.

### CODE REVIEW

**Comment by agarny** [comment]
Which issue does this address?...

**Comment by kerimoyle** [comment]
@agarny Oops, sorry, it's for #302 
What do I need to do to get the Clang thing working?

**Comment by agarny** [comment]
> What do I need to do to get the Clang thing working?

What do you mean by the Clang thing? Are you talking about Clang-Tidy (i.e. issue #283) and ClangFormat (i.e. issue #310)? If so, we first need for PR #310 to be merged in and then PR #288.

**Comment by nickerso** [comment]
Closing as this looks to be superseded by #353. Please reopen if I'm missing something...

**Pull request closed without merging**
