### PR TITLE
Fix configuration errors for CMake > 3.13

### PR DESCRIPTION
**Pull request by hsorby**
Addresses issue #395

### CODE REVIEW

**Comment by hsorby** [comment]
llvm 9.0.0 has thrown up some new clang-tidy errors.  I'm not sure what the criteria is for allowing or disallowing clang-tidy checks.  We will have to decide on some further inclusions/exclusions before any PR can be merged now that the build slave has been updated to llvm 9.0.  New issue anyone?

**Comment by agarny** [comment]
By "New issue anyone?" are you suggesting to create a new issue specifically for clang-tidy 9.0.0? If so, I would agree with it.

**Comment by hsorby** [comment]
> By "New issue anyone?" are you suggesting to create a new issue specifically for clang-tidy 9.0.0? If so, I would agree with it.

Done #397.

**Comment by agarny** [comment]
Yes, saw that after posting my comment above...!

**Comment by hsorby** [comment]
This bad boy should be ready to go, an important fix for all those VS2019 users out there.

**Review by agarny — APPROVED** [review]
Looks good to me, although I have no means of testing it locally (VS2017 user here).

**Comment by hsorby** [comment]
The VS2019 part is really only the inclusion of the `stdexcept` header.  The CMake part is because of CMake 3.13.

Time to upgrade!

**Comment by agarny** [comment]
Well, Qt doesn't officially support MSVC 2019, so not yet time to upgrade for me... :)

**Comment by nickerso** [comment]
I can confirm this change allows me to configure and generate (CMake 3.15.2) without error, including the python bindings. And in Visual Studio 2019 I can build without error. But all tests fail.

**Comment by hsorby** [comment]
all tests?

**Comment by hsorby** [comment]
Do you have libxml2 found using CMake *.cmake files?

**Comment by hsorby** [comment]
I get this when I run the tests:

```
1>100% tests passed, 0 tests failed out of 37
1>
1>Total Test time (real) =   7.47 sec
========== Build: 1 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
```

**Comment by nickerso** [comment]
I have the OpenCMISS libxml as per the build instructions. The python tests all fail and the C++ tests all still give exceptions. Is there any other PR I need to be pulling in?

```
2>	 32 - python_test_units (Failed)
2>	 33 - python_test_variable (Failed)
2>	 34 - python_test_validator (Failed)
2>	 35 - python_test_version (Failed)
2>	 36 - python_test_when (Failed)
2>	 37 - python_test_docstrings (Failed)
2>Errors while running CTest
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(138,5): error MSB3073: The command "setlocal
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(138,5): error MSB3073: "C:\Program Files\CMake\bin\ctest.exe" --force-new-ctest-process -C Debug
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(138,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(138,5): error MSB3073: :cmEnd
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(138,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(138,5): error MSB3073: :cmErrorLevel
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(138,5): error MSB3073: exit /b %1
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(138,5): error MSB3073: :cmDone
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(138,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(138,5): error MSB3073: :VCEnd" exited with code 8.
2>Done building project "RUN_TESTS.vcxproj" -- FAILED.
========== Rebuild All: 1 succeeded, 1 failed, 0 skipped ==========
```

**Comment by hsorby** [comment]
I would suspect that there are dlls that are not available to the test applications.

**Comment by agarny** [comment]
I have just tested this PR using MSVC 2017 and I am getting the same output as @nickerso (but referencing MSVC 2017, of course). When it comes to libxml2, I have:

Screen Shot 2019-09-27 at 08 47 24

**Comment by nickerso** [comment]
But the dlls part is something that surely wouldn't have changed between the VS 2015 on the CI system and VS 2017 and 2019?!  :-)

**Comment by hsorby** [comment]
No see, I don't think you have read the documentation properly.  If you use this method of defining the location of the libXml2 library you the user have to make sure that the libXml2 dll is on the path in the environment that the tests are run in.  If you use the LibXml2_DIR variable to define the location of the libXml2 libraries CMake can work out what it needs for the tests for you and add it to the test environment itself.  The LibXml2_DIR option can only be used when you use a build that has the `libxml2-config.cmake` and similar files.

**Comment by nickerso** [comment]
OK - this is what was causing me problems too. Changing my libXML2 to find using the config mode gave me a solution that builds fine and all the tests pass in VS 2019.

**Review by nickerso — APPROVED** [review]

**Pull request merged**
