### PR TITLE
Generator: further refinements to the generated C code

### LINKED ISSUE #938: Generator: further refinements to the generated C code
- [x] For an algebraic model, we don't need to define the `VariableInfo` structure (this was an oversight on my part in #901).
- [x] In C, to cast the output of `malloc()` is redundant (see [here](https://en.wikipedia.org/wiki/C_dynamic_memory_allocation#Type_safety)). To cast would normally allow our generated C code to be compilable by a C++ compiler, but then again any decent C++ compiler would complain our use of `malloc()`/`free()`. So, we may as well stick to the C standard.

### PR DESCRIPTION
**Pull request by agarny**
Fixes #938.

### CODE REVIEW

**Comment by agarny** [comment]
Note that I haven't updated the version of the code generator (too much work without a script!).

**Comment by hsorby** [comment]
You don't need to we haven't released that version of the code generator.

**Comment by agarny** [comment]
> You don't need to we haven't released that version of the code generator.

Indeed, so why did we bother in #901?

**Comment by nickerso** [comment]
> > You don't need to we haven't released that version of the code generator.
> 
> Indeed, so why did we bother in #901?

we only need to update the version once a given version has been released. The update from #901 was needed as the 0.2 profile version had been released, but now we are bumped up to 0.3 we're good with changes until the next release.

**Comment by agarny** [comment]
> > > You don't need to we haven't released that version of the code generator.
> > 
> > 
> > Indeed, so why did we bother in #901?
> 
> we only need to update the version once a given version has been released. The update from #901 was needed as the 0.2 profile version had been released, but now we are bumped up to 0.3 we're good with changes until the next release.

Doh! Makes sense indeed... 🙄

**Review by nickerso — APPROVED** [review]

**Review by hsorby — APPROVED** [review]

**Pull request merged**
