### PR TITLE
General: replace `getXxx()` with `xxx()` (#325)

### PR DESCRIPTION
**Pull request by agarny**
Addresses issue #325.

(Still need to update the doc diagrams.)

### CODE REVIEW

**Comment by agarny** [comment]
@hsorby, I would like to modify our different diagrams to replace the different `getXxx()` methods with `xxx()`, but what is the best way to go about this? I can see some files under `docs/masters`, which are probably the ones that need to be modified and some PNG files that need to be regenerated under `docs/images`?

**Comment by hsorby** [comment]
The master documents for generating the png files are on [lucidchart](https://www.lucidchart.com).  I edit these and then export them.  You need an account and then they can be shared (I think).

**Comment by agarny** [comment]
Yes, @nickerso told me about [Lucidchart](https://www.lucidchart.com/) and I have got myself an account there (a free one though), so I guess I would need to get access to those files...

**Comment by agarny** [comment]
Oh... and I am not sure I can edit files using a free account...?

**Comment by hsorby** [comment]
Should be able to I think my account is free?

**Comment by agarny** [comment]
What I know for certain is that if I import something then I can only view it, I can't edit it. So, I am just assuming it must be the same for something that has been shared? Whatever the case, I don't have access to the files, so...

**Review by hsorby — APPROVED** [review]
I have had a look at the code and I can't find anything to disapprove of it other than saying I haven't gotten used to the lack of `get` at this point.  So I'll approve it if other people prefer using the `get` prefix they should say so soon.

**Comment by agarny** [comment]
@hsorby / @nickerso: I wanted to update our master copy of `docs/masters/libCellMLObjectModel.vdx` and `docs/masters/libCellMLProcesses.vdx` with our "new" version in [Lucidchart](https://www.lucidchart.com/), but I can't export them to VDX. Can any of you do it?

**Comment by agarny** [comment]
Ping @hsorby / @nickerso re Lucidchart and @nickerso re approval. I would really like to see this PR merged in today, if possible... so we can then merge in PRs #344 and #322.

**Review by nickerso — APPROVED** [review]
Bump the updated object model images to a new issue.

**Pull request merged**
