### PR TITLE
Expose Entity->parent() as Model or Component for Python

### PR DESCRIPTION
**Pull request by kerimoyle**
Addresses #422 

... and yeah, I know there's no test, but that's because I can't figure out how to write one ... I just need to get the parent pointer in the correct typecast in python.  These changes do what I need, but not sure what others will think?

### CODE REVIEW

**Comment by hsorby** [comment]
I'm not a fan of this approach.  Trying alternatives without success so far.

**Comment by hsorby** [comment]
I have created an alternative to this in pull request #435 try it out and see if it works (it does for me).

**Comment by nickerso** [comment]
Should this one be closed in favour of #435 ? or is it still not clear what alternative to go with?

**Comment by hsorby** [comment]
I think this should be closed in favour of #435 waiting for an independent opinion on whether #435 works in the required situation or not.

**Comment by kerimoyle** [comment]
Works for me, so closing.

**Pull request closed without merging**
