### PR TITLE
Gtest upgrade

### PR DESCRIPTION
**Pull request by hsorby**
Upgrading gtest to version 1.8.0 to deal with VS 2017 generating warnings over 1.7.0.

Addresses #249.

### CODE REVIEW

**Review by nickerso — APPROVED** [review]
The gtest update clears up all the warnings I've been getting in VS 2017. Will need to get #248 merged before merging this one in.

**Comment by MichaelClerx** [comment]
Why is all the import stuff in here?

**Comment by agarny** [comment]
> Why is all the import stuff in here?

Mistake...

**Comment by MichaelClerx** [comment]
ok?

**Comment by nickerso** [comment]
can be merged once #248 gets merged...

**Comment by MichaelClerx** [comment]
I feel we're not getting the full benefit of GIT with these merging strategies :smile:

**Comment by agarny** [comment]
This PR has been superseded by PR #251, so closing.

**Pull request closed without merging**
