### PR TITLE
Issue302 Remove validation from parser

### PR DESCRIPTION
**Pull request by kerimoyle**
This is a very small change to the parser - only removes the checking for name attributes within units and variables as this is present in the validator instead.

Addresses #302

### CODE REVIEW

**Comment by kerimoyle** [comment]
Coverage test is failing here, but the log says it has 100% coverage.  Not sure where to go from here ...?

**Comment by agarny** [comment]
> Coverage test is failing here, but the log says it has 100% coverage. Not sure where to go from here ...?

Yes, there is indeed an issue with our CI system when it comes to coverage... @hsorby is on to it... :)

**Comment by kerimoyle** [comment]
Ready for review :)

**Review by nickerso — APPROVED** [review]
Looks fine to me. Might want to remove the reset related changes to avoid conflicts with future merges, but can always be resolved later.

**Comment by agarny** [comment]
> Looks fine to me. Might want to remove the reset related changes to avoid conflicts with future merges, but can always be resolved later.

Yes, could be done later.

I am waiting for all the tests to pass and will then merge this PR in.

**Review by agarny — APPROVED** [review]

**Comment by agarny** [comment]
@kerimoyle's first merged-in PR. Woo hoo! :)

**Pull request merged**
