### PR TITLE
Issue printing model with multiple imports

### PR DESCRIPTION
**Pull request by nickerso**
Investigating #474.

### CODE REVIEW

**Comment by hsorby** [comment]
Ready for review.

**Comment by nickerso** [comment]
Seems I am not allowed to approve this one as I started the pull request, even though @hsorby actually did the fix :)

**Comment by agarny** [comment]
> Seems I am not allowed to approve this one as I started the pull request, even though @hsorby actually did the fix :)

Yes, we have had that issue before between @kerimoyle and @hsorby. You guys... not learning, are you? :)

**Review by hsorby — APPROVED** [review]
Quite possibly the best solution, I fully approve this work!

**Review by agarny — APPROVED** [review]

**Pull request merged**
