### PR TITLE
Upgraded gtest to version 1.8.0

### PR DESCRIPTION
**Pull request by agarny**
Upgrading gtest to version 1.8.0 to deal with VS 2017 generating warnings over 1.7.0.

Addresses #249.

### CODE REVIEW

**Review by nickerso — CHANGES_REQUESTED** [review]
Still getting the tr1 namespace warnings in VS 2017. I'd also prefer to keep the versioned folder name...

**Comment by agarny** [comment]
FTR, this PR uses [gtest 1.8.0](https://github.com/google/googletest/releases/tag/release-1.8.0) while PR #250 was using [gtest's master branch](https://github.com/google/googletest).

Ideally, we would be waiting for gtest 1.9.0 to be released, but... gtest 1.8.0 was released in August 2016 and, prior to that, gtest 1.7.0 was released in September 2013. So, not quite sure when we can expect gtest 1.9.0 to be released...

So... do we want to drop support for VS 2017, use gtest's master branch or... do something else?

**Comment by nickerso** [comment]
the gtest in #250 worked fine with VS 2017 and all tests passed on our build systems, so I think we should go to the current master branch.

**Review by hsorby — APPROVED** [review]
Works for me, I think we'll let @nickerso test on his windows machine before merging this.

**Review by nickerso — APPROVED** [review]
This is working for me and clears up #249. Tests failing on mac due to known networking issues, will keep trying to get it through to confirm its all good to merge.

**Comment by nickerso** [comment]
Since we have moved to the current master version of gtest, I'm fine to remove the version string from the folder name.

**Pull request merged**
