### PR TITLE
Clear our error handler.

### PR DESCRIPTION
**Pull request by nickerso**
Need to make sure we leave libxml suitable for other applications to use. Addresses #179.

### CODE REVIEW

**Comment by hsorby** [comment]
Looks good but where's the test?  Pragmatically this change is good for merging.

**Comment by nickerso** [comment]
addressed comment from @hsorby, ready for review now.

**Comment by agarny** [comment]
Not 100% sure it follows our coding style, but apart from that it looks good to me.

Am I correct in remembering that we need someone else to to be happy with the PR before merging it? If not, let me know and I will happily merge it.

**Comment by hsorby** [comment]
We have been waiting for our ace reviewer to get back from holiday, but in the meantime we have tried hard to write @agarny level code.

**Comment by agarny** [comment]
At least, you don't seem to be needing a holiday, you are on top form! :)

**Pull request merged**
