### PR TITLE
Clang-Tidy: include libCellML's header files (#362)

### PR DESCRIPTION
**Pull request by agarny**
Addresses issue #362.

### CODE REVIEW

**Review by nickerso — APPROVED** [review]
looks good.

**Comment by agarny** [comment]
Argh, just noticed that commit 03e2f2a actually prevents Clang-Tidy from doing its thing on *all* header files!

**Comment by agarny** [comment]
Ping @nickerso and @hsorby. I think I am done with it...!

**Comment by agarny** [comment]
Ok, @hsorby and @nickerso, I need your opinion on this issue...

What we have at the moment, i.e.

```
set(_HEADER_FILTER_DIR "${CMAKE_SOURCE_DIR}/src/")
string(REPLACE "." "\\\."
       _HEADER_FILTER_DIR "${_HEADER_FILTER_DIR}")
string(REPLACE "/" "\\\/"
       _HEADER_FILTER_DIR "${_HEADER_FILTER_DIR}")

set_target_properties(${_TARGET} PROPERTIES
  CXX_CLANG_TIDY "${CLANG_TIDY_EXE};-checks=${_CLANG_TIDY_CHECKS};-header-filter=${_HEADER_FILTER_DIR}.*${_CLANG_TIDY_WARNINGS_AS_ERRORS}"
)
```

works fine... if you build libCellML using `make`. However, if you use `ninja` (as I do most of the time), then we won't get any Clang-Tidy issue with libCellML's header files. In order to see them, we need to use a relative path, e.g.

```
set_target_properties(${_TARGET} PROPERTIES
  CXX_CLANG_TIDY "${CLANG_TIDY_EXE};-checks=${_CLANG_TIDY_CHECKS};-header-filter=\\\.\\\.\\\/.*${_CLANG_TIDY_WARNINGS_AS_ERRORS}"
)
```

In other words, depending on the generator used with CMake, `CXX_CLANG_TIDY` has to be set differently (great!). Incidently, this might explain why I haven't managed to get things to work with Visual Studio (yet).

So, what should we do about this?...

**Comment by hsorby** [comment]
I'll verbalise what you have already thought:

I think adding a macro to generate the paths for the current generator is a reasonable solution.

**Comment by agarny** [comment]
This should definitely solve our problem, but... how do we go about that?

**Review by hsorby — COMMENTED** [review]
After #369 none of these flags need compiler version protection?

**Comment by agarny** [comment]
> After #369 none of these flags need compiler version protection?

Maybe, maybe not, I don't know since I am using the latest version of Xcode and I am not sure I want to install an old version... So, I guess it will be up to @0u812 to tell us how it goes once this PR has been merged in.

**Comment by agarny** [comment]
Actually, those are Clang-Tidy flags, not Clang flags, so we ought to be fine. The only thing, I think, is that we need to ensure that we are using a supported version of Clang-Tidy (see issue #356).

**Review by hsorby — COMMENTED** [review]
So we are now just waiting on a solution to the header file paths before this can be merged in.  Is that correct?

**Comment by agarny** [comment]
Correct.

**Comment by 0u812** [comment]
Many thanks for your help! The compiler flag problem is gone but I'm getting some compiler errors with these changes. Apparently, `ModelPtr` is missing a namespace qualifier somewhere. I'm on commit 896bcffe2b2ceabfcca529856f58710c38c7da2d which I believe should be this PR.
```
/Users/phantom/devel/build/libcellml-xcode/src/bindings/python/swig_intermediaries/validatorPYTHON_wrap.cxx:3150:3: error: unknown type name
      'ModelPtr'; did you mean 'libcellml::ModelPtr'?
  ModelPtr *arg2 = 0 ;
  ^~~~~~~~
  libcellml::ModelPtr
...
/Users/phantom/devel/src/libcellml/src/api/libcellml/types.h:39:7: note: 'libcellml::ModelPtr' declared here
using ModelPtr = std::shared_ptr<Model>; /**< Type definition for shared model pointer. */
      ^
/Users/phantom/devel/build/libcellml-xcode/src/bindings/python/swig_intermediaries/validatorPYTHON_wrap.cxx:3171:28: error: unknown type
      name 'ModelPtr'; did you mean 'libcellml::ModelPtr'?
  arg2 = reinterpret_cast< ModelPtr * >(argp2);
                           ^~~~~~~~
                           libcellml::ModelPtr
...
/Users/phantom/devel/build/libcellml-xcode/src/bindings/python/swig_intermediaries/validatorPYTHON_wrap.cxx:3172:26: error: unknown type
      name 'ModelPtr'; did you mean 'libcellml::ModelPtr'?
  (arg1)->validateModel((ModelPtr const &)*arg2);
                         ^~~~~~~~
                         libcellml::ModelPtr
```

**Comment by hsorby** [comment]
I'm not sure how you have ended up on here @0u812.  What happens when you try and build from a clean version of the develop branch?

**Comment by agarny** [comment]
> I'm not sure how you have ended up on here @0u812. What happens when you try and build from a clean version of the develop branch?

That's because I mentioned in [my comment above](https://github.com/cellml/libcellml/pull/363#issuecomment-505269167), but indeed that's not what @nickerso wanted @0u812 to check (see [here](https://github.com/cellml/libcellml/pull/369#issuecomment-505248261)).

**Comment by 0u812** [comment]
Oops looks like this is the wrong thread. The latest development branch works for me. Thanks!

**Comment by agarny** [comment]
Ok, I have edited this PR so that line 27 in `src/xmldoc.h` reads

```
typedef std::shared_ptr<XmlDoc> XmlDocPtr;
```

rather than

```
using XmlDocPtr = std::shared_ptr<XmlDoc>;
```

From there, I did the following:

```
mkdir build
cd build
cmake ..
make
.
.
.
/Users/Alan/libCellML/src/xmldoc.h:27:1: error: use 'using' instead of 'typedef' [modernize-use-using,-warnings-as-errors]
typedef std::shared_ptr<XmlDoc> XmlDocPtr; /**< Type definition for shared XML doc pointer. */
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
using XmlDocPtr = std::shared_ptr<XmlDoc>
8676 warnings generated.
Suppressed 8675 warnings (8675 in non-user code).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
1 warning treated as error
.
.
.
```

which is exactly what I would expect.

Now, if I try the same using Ninja as generator:

```
cd ..
rm -fr build
mkdir build
cd build
cmake -G Ninja ..
ninja
.
.
.
[139/139] Linking CXX executable tests/test_connection
```

In other words, I don't get told about the "issue" with `xmldoc.h`.

From there, I edited line 177 of `cmake/common.cmake` to read:

```
CXX_CLANG_TIDY "${CLANG_TIDY_EXE};-checks=${_CLANG_TIDY_CHECKS};-header-filter=\\\.\\\.\\\/src\\\/.*${_CLANG_TIDY_WARNINGS_AS_ERRORS}"
```

rather than

```
CXX_CLANG_TIDY "${CLANG_TIDY_EXE};-checks=${_CLANG_TIDY_CHECKS};-header-filter=${_HEADER_FILTER_DIR}.*${_CLANG_TIDY_WARNINGS_AS_ERRORS}"
```

and rebuilt everything using Ninja:

```
cd ..
rm -fr build
mkdir build
cd build
cmake -G Ninja ..
ninja
.
.
.
/Users/Alan/libCellML/build/../src/xmldoc.h:27:1: error: use 'using' instead of 'typedef' [modernize-use-using,-warnings-as-errors]
typedef std::shared_ptr<XmlDoc> XmlDocPtr; /**< Type definition for shared XML doc pointer. */
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
using XmlDocPtr = std::shared_ptr<XmlDoc>
16087 warnings generated.
.
.
.
```

So, this time, it all works as expected, but if I use Make again (with the "new" value for `-header-filter`) then things don't work anymore:

```
cd ..
rm -fr build
mkdir build
cd build
cmake ..
make
.
.
.
[100%] Built target test_math
```

In conclusion: the format of the path reported by Clang-Tidy depends on the generator used with CMake, which means that we cannot come up with a solution that works with any CMake generator. The situation would be different if `-header-filter` required a PCRE regular expression (rather than a POSIX ERE one). Indeed, we could filter out the folders in which we are not interested by using something like `^(?:(?!xxx|yyy|zzz).)*$`, i.e. a regular expression with a non-capturing group and a negative lookahead.

**Comment by nickerso** [comment]
But we can have a generator-dependent regex that we can implement for the generators that we know are commonly used (i.e., the ones on the CI system + the ones that the dev team use), right? or is that not possible either?

**Comment by agarny** [comment]
Sure, we could easily have a regex for Ninja and Make (as I have kind of done above), but when it comes to Windows, it's a bit of a mess since we can use `NMake Makefiles JOM` and different `Visual Studio XXX` generators (see [here](https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html)).

To be honest, for OpenCOR, I have settled for Ninja and assumed that it is being build from  `[OpenCOR]/build`. Now, I appreciate that we may want to be a bit more generic when it comes to libCellML...

**Comment by agarny** [comment]
Ping @hsorby.

**Comment by agarny** [comment]
Ok, I think 021ebfa is my final commit for this issue. In summary:
 - Clang-Tidy does, by default, report issues with C++ files. When it comes to header files, we must let Clang-Tidy know for which ones of them we want issues to be reported... and this is where things get a bit tricky since it indirectly depends on the CMake generator used.
 - This PR can report issues with header files when using either Make or Ninja as a CMake generator (when it comes to the Ninja generator, we must build libCellML from `[libCellML]/build` otherwise issues with header files won't be reported). This means that this PR works fine with both our CI system and our Docker file.

**Comment by agarny** [comment]
@hsorby, @nickerso and @kerimoyle... feel free to (re)review this PR... :) (@kerimoyle, I can't put you as a reviewer for now, but feel free to add yourself once you have agreed to be part of the "team".)

**Review by kerimoyle — APPROVED** [review]
Looks fine ... :)

**Comment by agarny** [comment]
> Looks fine ... :)

Woo hoo! Ok, so either @nickerso or @kerimoyle can merge this in. :)

**Pull request merged**
