### PR TITLE
Instantiate invalid imports

### PR DESCRIPTION
**Pull request by kerimoyle**
Addresses #663 

This PR is built on top of #653 so should be merged after that one.  It removes checks for errors in the `Parser` that prevented incomplete imported items from being added to the model.

### CODE REVIEW

**Comment by kerimoyle** [comment]
NB: this is actually a really small PR, but it's built on top of a big one.  For review purposes, you need to only look at two commits: 13bccff and 682edf0.  It won't be merged until #653 is merged.  Other than that, it's ready for review @nickerso @agarny @hsorby

**Comment by agarny** [comment]
Seems to be fine, but will confim once PR #653 has been merged in and this PR has been updated accordingly.

**Comment by kerimoyle** [comment]
Ping @agarny @hsorby @nickerso This is a tiny PR, and now that the one it depends on has been merged, should be quite straightforward to review?

**Review by agarny — APPROVED** [review]

**Review by nickerso — APPROVED** [review]
looks good, probably good to wait on CI to check things before merging ;-)

**Pull request merged**
