### PR TITLE
CMake: prevent a lot of warnings when building our Python bindings using Python 3.8 on macOS

### PR DESCRIPTION
**Pull request by agarny**
Addresses issue #665.

### CODE REVIEW

**Review by nickerso — COMMENTED** [review]
not sure how to review this as I don't have a Mac and this change shouldn't affect the CI...

**Comment by agarny** [comment]
> not sure how to review this as I don't have a Mac and this change shouldn't affect the CI...

I know... :) Still, that issue has been bugging me ever since Homebrew upgraded Python to Python 3.8, so... it would be nice to have it in... :) At the end of the day, this PR does something similar to what we are already doing for Clang-Tidy (see [here](https://github.com/cellml/libcellml/blob/4eda134eac1232695ce6a9b06e060810a7bd2020/cmake/common.cmake#L91-L123)).

**Review by nickerso — APPROVED** [review]
CI is happy, so probably safe to approve this one.

**Comment by kerimoyle** [comment]
Even having a Mac I can't test this as I don't run Python 3.8! Does @hsorby have it? Should we have at least one person actually able to see if it works before approving ...?

**Comment by agarny** [comment]
> Even having a Mac I can't test this as I don't run Python 3.8! Does @hsorby have it? Should we have at least one person actually able to see if it works before approving ...?

How was your copy of Python installed? Using Homebrew? If so, you can upgrade it using `brew upgrade` and then you can do `brew cleanup -s` to remove any unnecessary files, if you want (to save disk space). From there, you should test the `develop` branch to confirm the warnings, and then test my `issue665` branch to confirm that it doesn't generate warnings anymore.

**Review by hsorby — APPROVED** [review]

**Pull request merged**
