### PR TITLE
Math parser: provide a way to ignore validation using the MathML DTD

### PR DESCRIPTION
**Pull request by agarny**
Addresses issue #551.

### CODE REVIEW

**Review by hsorby — APPROVED** [review]

**Comment by agarny** [comment]
Ping @nickerso and @kerimoyle. This is a very trivial PR.

**Comment by kerimoyle** [comment]
Sorry Alan, from your comments I didn't realise it was finished!

**Comment by agarny** [comment]
It's finished, it's just that it doesn't provide me with the super duper speed up I was hoping for, unfortunately.

**Comment by kerimoyle** [comment]
Should this one go together with a solution to #557 since they're dealing with the same thing?

**Comment by agarny** [comment]
Although they are both related to MathML, they are not dealing with the same "issue". So, I would just like to see this PR merged in, if everybody is happy with it.

**Review by kerimoyle — APPROVED** [review]

**Comment by kerimoyle** [comment]
Yep, is fine with me.

**Pull request merged**
