### PR TITLE
Added some status information to README.rst

### PR DESCRIPTION
**Pull request by agarny**
Addresses issue #270.

### CODE REVIEW

**Review by hsorby — COMMENTED** [review]
I probably wouldn't go with the all-caps text and I do feel this should be evident through the use of the version numbers and a reference to semantic versioning.

**Comment by agarny** [comment]
That's the thing, based solely on the version number, I wouldn't normally use libCellML (I mean, version 0.1/0.2...!). Yet, it can already be useful to people. It all depends on what you want to do with it. However, one should indeed keep in mind that the API may change at any stage while we haven't reached version 1.0 (as it has on several occasions already).

Anyway, let's see whether @nickerso and @MichaelClerx's view has changed on this.

**Comment by nickerso** [comment]
maybe worth looking at adding some badges to the repo/readme instead? Must be some kind of version info badge?

Otherwise agree with @hsorby's suggestion to not use ALL-CAPS :)

**Comment by agarny** [comment]
The caps were, obviously, used on purpose: to make sure that people don't overlook it (how many people have read the README.rst?).

Not sure about badges: too much hassle for something so trivial.

**Review by MichaelClerx — DISMISSED** [review]
I don't even mind the all-caps :-)

Never seen a badge for development status, wouldn't look there myself - Would much prefer writing at the very start that this is not ready for use, instead of writing as if it's ready but with some hidden disclaimer among the badges :D

**Review by nickerso — APPROVED** [review]

**Comment by nickerso** [comment]
whoops, forgot that making changes would dismiss reviews - I just changed one word and happy to accept @MichaelClerx's earlier approval as still valid...

**Comment by agarny** [comment]
I think it's fair enough, so FWIW happy for you to force the merge.

**Pull request merged**
