### PR TITLE
Create analyser test showing segfault due to unlinked Units.

### PR DESCRIPTION
**Pull request by hsorby**
Addresses #883.

### CODE REVIEW

**Comment by agarny** [comment]
@hsorby, I wanted to edit your [segfault-unlinked-units](https://github.com/hsorby/libcellml/tree/segfault-unlinked-units) branch, but I can't seem to be able to do that? GitHub desktop tells me that it "couldn't find branch 'segfault-unlinked-units' in remote 'hsorby'. A common cause for this is if the PR author has deleted their branch or their forked repository." So, am thinking of closing this PR and creating my own branch using the content of this PR...?

**Comment by hsorby** [comment]
This is clearly not the case as you can see the branch in my fork.

**Comment by hsorby** [comment]
I would prefer it if you didn't do as proposed.

**Comment by agarny** [comment]
> I would prefer it if you didn't do as proposed.

Definitely my preference too. Will try again later.

**Comment by agarny** [comment]
Not sure what I did wrong in the first place, but I have just removed your remote and readded it, and it's all fine now. 🤷 (So, going to use this PR.)

**Review by agarny — APPROVED** [review]

**Review by nickerso — APPROVED** [review]
Will need to add documentation at some point for users to understand the unlinked units issue from the analyser...

**Pull request merged**
