### PR TITLE
Address Entity parents.

### PR DESCRIPTION
**Pull request by hsorby**
This is how I think parents of entities should be handled.

Adresses #320.

### CODE REVIEW

**Comment by kerimoyle** [comment]
This feels like going backwards in time ... we've only just changed into differentiating between parentModel and parentComponent types, which is actually really useful in validation.  It would be great to be able to use that same functionality (ie - two separate functions) to retrieve both the parent model (even if the component is a long way down an encapsulation chain) as well as the component's immediate parent component.  I don't see that functionality present here any more?  

I would love to have something like:

```
model->addComponent(c1)
c1->addComponent(c2)
c2->addComponent(c3)

c1->addVariable(v1)
c2->addVariable(v2)
c3->addVariable(v3)

v1->parentModel = model
v1->parentComponent = c1

c1->parentComponent = nullptr
c1->parentModel = model

c2->parentComponent = c1
c2->parentModel = model

... etc ...
```

**Comment by hsorby** [comment]
If you look at the `utilities.h` header file I have added a function `parentModel` that retrieves the owning model of the entity if there is one.

**Comment by kerimoyle** [comment]
Missed that, thanks :)  So we assume the type of object returned by `parent()` is always a component?  and parentModel() always a model?  Could we not just keep the parentComponent() name then, just for clarity?

**Comment by hsorby** [comment]
Nope, `parent()` can return a model.

**Comment by kerimoyle** [comment]
Yeah, that's not great ... then every time you call parent() you'd have to test for type before knowing how to handle it... that's what the changes in the earlier PR https://github.com/cellml/libcellml/pull/322 were written to fix?

**Comment by agarny** [comment]
> Yeah, that's not great ... then every time you call parent() you'd have to test for type before knowing how to handle it... that's what the changes in the earlier PR #322 were written to fix?

Indeed, I don't like the idea of having to `static_cast` something to determine whether we are dealing with a parent component or a parent model. It's not clean.

**Comment by hsorby** [comment]
This is kind of how C++ works with inheritance and so on, and anyway you wouldn't be doing a static cast it would have to be .a dynamic one :)

**Comment by kerimoyle** [comment]
It is how C++ works with inheritance, but I don't think that having parents in the highest level entity make sense if they're not actually used anywhere except the components?  Why not just define a parentModel and parentComponent pointer in the components and remove the parent pointer from the entity?

**Comment by hsorby** [comment]
`units` and `variables` have parents?

**Comment by kerimoyle** [comment]
.. but where do we actually use them?

**Comment by hsorby** [comment]
I think they will be used when we look at the `addVariable` and `removeVariable` again and realise that it is not working as desired.

**Review by nickerso — APPROVED** [review]
I like this approach. Entities should not need to know anything about derived types.

**Comment by kerimoyle** [comment]
> Entities should not need to know anything about derived types.

True ... but overall I think that our use of inheritance here actually gets in the way of the functionality.  What's wrong with defining parents explicitly in the few cases we need them?  Of course it's possible to use inheritance to define the parent pointer, but as it makes other parts of the code a lot more clumsy, I don't see the advantage?

> I think they will be used when we look at the addVariable and removeVariable again and realise that it is not working as desired.

... could you be a bit more specific about that?  Sorry for all the questions, I just don't understand this PR.

**Review by agarny — APPROVED** [review]
I find that it makes the API more cumbersome to use, but... ok, let's see how it goes in the long run...

**Pull request merged**
