### PR TITLE
Debug functions automatically available in Debug configurations

### PR DESCRIPTION
**Pull request by hsorby**
Addresses #567.

### CODE REVIEW

**Comment by hsorby** [comment]
I have reverted to adding a library that is linked in at compile time as MSVC cannot handle configuration dependent source files.

Doing this allows the use of the `Debug()` class for printing out messages in both release and debug configurations. But does not allow the use of the functions defined in `debug.cpp` in release configurations.

**Comment by hsorby** [comment]
We have no check to determine if `debug.h` is being included from the library proper.

**Comment by agarny** [comment]
@hsorby, is that ready to be reviewed?

**Comment by hsorby** [comment]
Yes it is.

**Review by agarny — APPROVED** [review]
Looks good to me.

**Comment by agarny** [comment]
@nickerso / @kerimoyle, if you could have a look at this PR. It's a simple one to review. :)

**Review by nickerso — APPROVED** [review]

**Pull request merged**
