### PR TITLE
Rename target for llvm_coverage_missing_lines

### PR DESCRIPTION
**Pull request by hsorby**
Addresses #789.

### CODE REVIEW

**Comment by hsorby** [comment]
This one should be a quick one to agree or disagree with :)

**Review by nickerso — COMMENTED** [review]
I thought this one would be about making the LLVM coverage name consistent with the python coverage report...but you are also changing the python name to remove the `html` ? so shouldn't the LLVM coverage just be `llvm_coverage_report` ?

**Comment by agarny** [comment]
> I thought this one would be about making the LLVM coverage name consistent with the python coverage report...but you are also changing the python name to remove the `html` ? so shouldn't the LLVM coverage just be `llvm_coverage_report` ?

Indeed, that's what I would have expected too.

**Comment by hsorby** [comment]
The target names and output directories are now `*_report` and `coverage_report` respectively for both llvm and python.

**Review by nickerso — APPROVED** [review]

**Review by agarny — APPROVED** [review]

**Comment by agarny** [comment]
Closes issue #789.

**Pull request merged**
