### PR TITLE
BUGFIX: CMake 3.11 changed the directory lookup.

### PR DESCRIPTION
**Pull request by rblake-llnl**
This broke the build.

Fixed as per @hsorby

### CODE REVIEW

**Comment by hsorby** [comment]
I think that we are going to have to merge this as our MacOS build slave is now using CMake 3.11.  This means that no knew code can be merged as the CI will always fail.

**Comment by agarny** [comment]
Ok, happy for you, @hsorby, to merge this PR then.

**Comment by hsorby** [comment]
I think @MichaelClerx or @nickerso will have to do it I am powerless in this regard.

**Comment by agarny** [comment]
Ok, I am going to do it then. :)

**Comment by MichaelClerx** [comment]
Uhm, wasn't the build failing?

**Comment by agarny** [comment]
@MichaelClerx, yes, but my understanding from what @hsorby said is that it cannot pass because "the CI will always fail [on macOS]."

**Comment by MichaelClerx** [comment]
Ok. I think we should start using shorter PRs (like this one) for any cmake or configuration changes, merge them with `develop` and then rebase the long-term branches like `resets` onto develop occasionally so that all big branches can benefit from all fixes!
Now we've got a weird situation with requiring merges to be made in a specific order etc., not really getting the benefit of git!

**Pull request merged**
