### PR TITLE
Fix bug in how standardMultipliers are used in the validator

### PR DESCRIPTION
**Pull request by kerimoyle**
Addresses #525

### CODE REVIEW

**Comment by kerimoyle** [comment]
Review please @hsorby @awickens @agarny @nickerso

**Comment by agarny** [comment]
I can see that you fixed something, but... without having had a proper look at the underlying problem, why no test has been modified?

**Comment by kerimoyle** [comment]
Because no test can exist at this stage - the bug is in something which is currently a warning, not an error.  Perhaps see the equivalent fix in action on the other branch (where there is a test?) #521

**Comment by agarny** [comment]
Ok, we probably ought to ignore this PR and focus on PR #521 instead.

**Comment by kerimoyle** [comment]
Closing as this fix is now in #554 .

**Pull request closed without merging**
