### PR TITLE
Add a requirements() function to the Importer class

### PR DESCRIPTION
**Pull request by kerimoyle**
Addresses #769 

This PR builds on the bug fix in #774 so should be merged after that on.

The main motivation for this PR is to make it possible for people who've used the `Importer` class to create or debug collections of models, to then output the repaired model as well as any repaired dependencies.

### CODE REVIEW

**Comment by kerimoyle** [comment]
Ready for review please @hsorby @agarny @nickerso

**Comment by kerimoyle** [comment]
This build is being skipped?  I'm not sure why?  @hsorby do you have a magic button to trigger it please?

**Comment by agarny** [comment]
> This build is being skipped? I'm not sure why? @hsorby do you have a magic button to trigger it please?

Same with PR #650 which has been hanging up since I updated it a couple of hours ago... :/

**Comment by hsorby** [comment]
Closing this because it cannot be edited in favour of #831.

**Pull request closed without merging**
