### PR TITLE
Use target_compile_features function.

### PR DESCRIPTION
**Pull request by hsorby**
target_compile_features function propagates compiler flags onto consuming projects via the INTERFACE_COMPILE_FEATURES flag of exported targets.  Simply setting the required CXX standard via properties does not do this.

Addresses #428.

### CODE REVIEW

**Review by nickerso — DISMISSED** [review]
Haven't had a chance to test this, but looks like it should work.

**Comment by hsorby** [comment]
If you are interested in testing the following might help (some of which has been modified from #425.)

 [Assumes hsorby is a label for https://github.com/hsorby/libcellml.git, 'libcellml' is the name of the directory libcellml is cloned too, you are on a Unices based machine.]

```
git fetch hsorby export_compiler_features_i428
git checkout -b temp_test hsorby/export_compiler_features_i428
cd ..
mkdir tmp_build
cd tmp_build
cmake -DINSTALL_PREFIX=../install-libcellml ../libcellml
make -j4
make install
```

Then:

```
cd ..
mkdir tmp_app
mkdir tmp_app_build
cd tmp_app
```

In the `tmp_app` directory create the following two files with the contents as specified:

CMakeLists.txt
```
cmake_minimum_required(VERSION 3.10.2)
project(test_app VERSION 0.1.0)

find_package(libCellML REQUIRED)

add_executable(test_app main.cpp)
target_link_libraries(test_app PUBLIC cellml)
```

main.cpp
```
#include <iostream>
#include <libcellml>

int main()
{
  std::cout << "Hello libCellML!" << std::endl;
  libcellml::Parser parser;
}
```

Then configure and build the application:
```
cd ../tmp_app_build
cmake -DCMAKE_PREFIX_PATH=../install-libcellml ../tmp_app
make
```

The run the application:
```
./test_app
```

You should get the following output:
```
Hello libCellML!
```

**Comment by kerimoyle** [comment]
Thanks @hsorby.  I've tried your test and got it going with a couple of tweaks.   FYI this is what I got when trying to build the new project:
`cmake -DCMAKE_PREFIX_PATH=../install-libcellml ..`

Gives output:
```
-- The C compiler identification is AppleClang 10.0.1.10010046
-- The CXX compiler identification is AppleClang 10.0.1.10010046
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:4 (find_package):
  By not providing "FindlibCellML.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "libCellML", but CMake did not find one.

  Could not find a package configuration file provided by "libCellML" with
  any of the following names:

    libCellMLConfig.cmake
    libcellml-config.cmake

  Add the installation prefix of "libCellML" to CMAKE_PREFIX_PATH or set
  "libCellML_DIR" to a directory containing one of the above files.  If
  "libCellML" provides a separate development package or SDK, be sure it has
  been installed.
```

I just needed to specify the child directories too, and then it worked fine:

`cmake -DCMAKE_PREFIX_PATH=../install-libcellml/lib/cmake/libCellML .. `

So I have a couple of questions:
- What's the reason for the single "../" at the beginning of the command above?  The actual relative path from the current place is two directories down not just one?
- Are we planning on distributing libCellML so that people need to build their own copy (like this), or are we aiming for precompiled libraries somehow instead?

**Comment by hsorby** [comment]
You or I may have missed a `cd ..` so we could be one level out.  Disclaimer: I didn't actually test the above commands just straight outta my head.

**Comment by hsorby** [comment]
> * What's the reason for the single "../" at the beginning of the command above?  The actual relative path from the current place is two directories down not just one?

Could be a mistake in the instructions.

> * Are we planning on distributing libCellML so that people need to build their own copy (like this), or are we aiming for precompiled libraries somehow instead?

Pre-compiled binaries somehow but still want instructions on using built libraries or installed libraries from own build.

**Comment by kerimoyle** [comment]
> You or I may have missed a `cd ..` so we could be one level out. Disclaimer: I didn't actually test the above commands just straight outta my head.

That's what I thought too, but when I added in the extra `../` to make it make sense (to me..) it didn't work.  Your way was right, but I don't understand why!

**Comment by hsorby** [comment]
I have tested my own commands now and believe I have it right, if you try and follow them again they should work 🤞

**Comment by hsorby** [comment]
> Your way was right, but I don't understand why!

Not sure I understand this, which way was right?

**Comment by kerimoyle** [comment]
This worked:
`cmake -DCMAKE_PREFIX_PATH=../install-libcellml/lib/cmake/libCellML ..`

- single `../` not the double that I would have expected
- exact path to the config file needed; just the install directory path was not enough.

**Comment by hsorby** [comment]
Strange, the base directory of the install root works for me.  You could try the absolute path to the install root and see what happens.  From a fresh build directory of course.

**Comment by kerimoyle** [comment]
The base directory worked the second time, but only after passing the full
path the first time. I guess there are leftovers somewhere ...

**Review by nickerso — APPROVED** [review]
Can confirm that @hsorby's directions worked perfectly for me.

**Comment by hsorby** [comment]
Anybody else able to review this pretty simple pull request.

**Review by agarny — APPROVED** [review]
Can confirm that @hsorby's directions also work for me.

**Pull request merged**
