### PR TITLE
Requirements check

### PR DESCRIPTION
**Pull request by hsorby**
Checking for gcov, valgrind and python interpreter (Python is required as the testing is wrapped in a Python script for both gcov and valgrind).

Addresses issue #12

### CODE REVIEW

**Comment by nickerso** [comment]
This seems good to me, and better than a noisy failure :)

**Comment by nickerso** [comment]
@miriams - when merging if you can add a comment like "closes #12" or similar just to get the issue to close when the pull request is merged in....thanks!

**Comment by agarny** [comment]
The second reviewer might also want to confirm that s/he agrees with the pull request before actually doing the merging (even though the merging kind of implies it).

**Comment by jonc125** [comment]
Personally I think the act of merging is sufficient confirmation!

**Comment by mirams** [comment]
Ah - OK!

On 11 May 2015 at 11:31, David Nickerson notifications@github.com wrote:

> @miriams https://github.com/miriams - when merging if you can add a
> comment like "closes #17 https://github.com/cellml/libcellml/pull/17"
> or similar just to get the issue to close when the pull request is merged
> in....thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cellml/libcellml/pull/17#issuecomment-100861621.

## 

Dr Gary Mirams
Wellcome Trust & Royal Society Sir Henry Dale Fellow
Computational Biology,
Dept. of Computer Science,
University of Oxford,
Wolfson Building,
OX1 3QD.
+44 (0)1865 610671
http://www.cs.ox.ac.uk/people/gary.mirams/

**Pull request merged**
