### PR TITLE
Update use-cases diagram with proposed load XML methods

### PR DESCRIPTION
**Pull request by dladd**
This updates the use-cases diagram with features to satisfy the 'Load' use-cases step (3).

This incorporates the use of LibXML2 for parsing XML strings and documents through the wrapper classes `XmlDoc` and `XmlNode`. 

In this proposal, "deserialise" methods are used, consistent with our "serialise" methods. Another strategy that has been mentioned in #111 is the possibility of using a separate parser. In addition to `doDeserialisation()` functions (not explicitly pictured in the diagram) on each of the deserialisation targets, I'm anticipating convenience functions to deserialise connections and encapsulations in `Model`.

Addresses part of #111

### CODE REVIEW

**Comment by agarny** [comment]
This seems fine to me, as a starting point.

Just one thing: I am not sure about 'deserialisation'. In the end, I am wondering whether I wouldn't personally prefer to have `import()` and `export()` methods rather than `deserialisation()` and `serialisation()`?

**Comment by nickerso** [comment]
I'd worry about conflicting interpretation of `import` in relation to CellML imports.

**Comment by agarny** [comment]
> I'd worry about conflicting interpretation of `import` in relation to CellML imports.

Hmm, good point! I still don't like 'deserialisation' though... :) (I think I can live with it though. :))

**Comment by dladd** [comment]
We could maybe swap "deserialise" with "load" or "read"? I'm not sure what would be most clear to a user... "Deserialise" is probably closest to what it actually does but is not necessarily a common phrase.

**Comment by agarny** [comment]
No, having 'serialise', it does indeed make sense to have 'deserialise'. (I am sure I will get used to it.)

**Comment by dladd** [comment]
Updated with separate parser class per comments in #111

**Comment by nickerso** [comment]
Just to be clear, I believe for now all we need is the `parseModel` methods.

**Comment by dladd** [comment]
Fair enough- updated now. I think it still makes sense to modularise the `loadA(APtr, XmlNodePtr)` methods as part of this. But we can add `parseA(string)` methods when/if we need them.

**Comment by agarny** [comment]
Looks OK to me.

**Comment by dladd** [comment]
This has now been updated to match the discussion to date and implementation from #114. I've left out the entity error classes (e.g., `VariableError`, `ImportError`, etc) for now as this is getting a bit crowded if we want to keep this to A4. I'm wondering if it might be better to have another sub-diagram for our error handling/validation. Any preferences?

**Comment by hsorby** [comment]
I would put these error classes on the main object model diagram and not this rough object model diagram.  Although I would be tempted to put a little marker down to make people aware of them.

**Comment by dladd** [comment]
Sounds good @hsorby . That diagram is probably due for an update now anyway :)

**Comment by nickerso** [comment]
I think this one is ready to be merged, right?

**Pull request merged**
