### PR TITLE
Update use-cases object model to Modify step (2)

### PR DESCRIPTION
**Pull request by dladd**
Adds `remove...()` methods to the object model diagram to satisfy the Modify use-cases step (2). Also adds existing `ComponentEntity` units features to the diagram. Since changes can be a bit difficult to track in an image, I've added a list of the new methods below.

Addresses part of #104 
### Component

| Method | Description |
| --- | --- |
| removeVariable(VariablePtr): void | removes argument from this component's mVariables |
| removeAllVariables(): void | resets this component's mVariables collective attribute |
| setMath(std::string): void | sets/removes the math string; to replace removeMath() |
### ComponentEntity

| Method/Attribute | Description |
| --- | --- |
| mUnits | collective Units attribute; currently exists in code but not object model |
| addUnits(UnitsPtr): void | add argument to this mUnits; currently exists in code but not object model |
| removeUnits(UnitsPtr): void | remove UnitsPtr from this mUnits |
| removeUnits(std::string): void | remove named units from this mUnits |
| removeAllUnits(): void | resets this component entity's mUnits |
| unitsCount(): const size_t | returns the number of units in this component entity |
| removeComponent(ComponentPtr): void | removes component by pointer |
| removeAllComponents(): void | removes all components from this component entity |
### Units

| Method | Description |
| --- | --- |
| removeUnit(std::string): void | removes named unit from this mUnits |
| removeAllUnits(): void | resets this units' mUnits |
| unitCount(): const size_t | returns the number of units that compose this units |
### Variable

| Method | Description |
| --- | --- |
| removeEquivalence(VariablePtr,VariablePtr): void | static; removes equivalence with reciprocity, calls v1->unsetEquivalentTo(v2) and v2->unsetEquivalentTo(v1) |
| removeAllEquivalences(): void | resets this variable's mEquivalentVariables |
| unsetEquivalentTo(VariablePtr): void | private; opposite function to setEquivalentTo(), removes instance of the argument variable in this variable's mEquivalentVariables |

### CODE REVIEW

**Comment by agarny** [comment]
For `ComponentEntity::removeUnits()`, we might want to have a version that takes a `std::string` as an input. In other words, to do something similar to what is done/suggested for `Component::removeVariable(...)`.

I would use `Variable::removeAllEquivalences()` rather than `Variable::removeAllEquivalentVariables()`, and thus be more in sync with say `Component::addVariable()`, `Component::removeVariable()` and `Component::removeAllVariables()`.

Otherwise, shouldn't there be a composition link between `ComponentEntity` and `Units`?

**Comment by dladd** [comment]
Thanks- I've now updated this per @agarny 's comment. I also swapped `removeMath()` with `setMath(std::string)` per discussion in the parent issue and updated the variable interface routines per the changes from #105.

**Comment by nickerso** [comment]
looks good to me.

**Comment by dladd** [comment]
I've also now added `ComponentEntity::unitsCount()` and `Units::unitCount()` to this to be consistent with our other collective attributes.

**Pull request merged**
