### PR TITLE
Fix an issue when initialising a state variable using a variable instead of a constant

### LINKED ISSUE #1144: An issue when initialising a state variable using a variable instead of a constant
`libcellml 0.4.0`

When I tried to write python code from the attached CellML model, I got the issues:
The method "analyse_model" found 2 issues:
    - Variable 'q_Ai' in component 'BG_initTest' is initialised using variable 'q_Ai_init', which is not a constant.
    - Variable 'q_Ao' in component 'BG_initTest' is initialised using variable 'q_Ao_init', which is not a constant.
 
[cellml.zip](https://github.com/cellml/libcellml/files/11143983/cellml.zip)

### PR DESCRIPTION
**Pull request by agarny**
Fixes #1144.

### CODE REVIEW

**Review by hsorby — COMMENTED** [review]
My first comment would be is this a minimal example that illustrates the issue?  It seems to me to be a model that highlights the bug in question.

**Comment by agarny** [comment]
> My first comment would be is this a minimal example that illustrates the issue? It seems to me to be a model that highlights the bug in question.

It is indeed. I just went for the model given to us by @WeiweiAi in issue #1144. I am happy to simplify it, if really needed.

**Review by nickerso — DISMISSED** [review]
I agree that the model to illustrate this issue could be much more minimal. But I can also see benefit in using models contributed by users as part of the bug report...

**Comment by hsorby** [comment]
I think this full model should be added to tutorials or as an end-to-end test.  These tests are unit tests, that is, trying to put the minimal groundwork in place to illustrate a particular issue.  I am in favour of reducing the model to the bare minimum required to create the failing situation.

**Comment by agarny** [comment]
Ok, now using a minimal model.

**Review by nickerso — APPROVED** [review]

**Review by hsorby — APPROVED** [review]

**Pull request merged**
