### PR TITLE
Issue 324 Moved hardcoded definitions to utilities.h

### PR DESCRIPTION
**Pull request by kerimoyle**
- hardcoded built-in and standard units, prefixes, and mathml tags are moved to the common.h file
- celsius is removed from builtin units list
- tests updated to remove celsius
- .gitignore changed to exclude VSCode files

Addresses issue #324 and its comments

### CODE REVIEW

**Comment by agarny** [comment]
@kerimoyle, it looks like there are some conflicting files (according to GitHub at least!). Would be good for you to resolve them before I review your PR.

**Comment by kerimoyle** [comment]
@agarny Good to go :)

**Review by agarny — APPROVED** [review]
@kerimoyle, as you will have seen, I have edited your PR a bit, so that the code looks consistent with the rest of libCellML's code. I also put the contents of `common.h` into `utilities.h`, as originally suggested by @hsorby and myself.

So, now, as this PR is fine for me to be merged in (even though it does contain things that are not currently used...  I am talking about `standardPrefixList`, for example).

**Review by nickerso — APPROVED** [review]

**Comment by kerimoyle** [comment]
> So, now, as this PR is fine for me to be merged in (even though it does contain things that are not currently used... I am talking about standardPrefixList, for example).

Thanks @agarny ... but I don't understand what you mean about not being used?  That array is used in the `isStandardPrefixName` function?  Or did that not make it?

```
bool Validator::ValidatorImpl::isStandardPrefixName(const std::string &name)
{
    bool result = false;
    if (standardPrefixList.count(name) != 0) {
        result = true;
    }
    return result;
}
```

**Comment by agarny** [comment]
Sorry, I didn't mean `standardPrefixList`, but `standardMultiplierList`. As far as I can tell, it's not used anywhere, at this stage.

**Pull request merged**
