### PR TITLE
Test to demonstrate segfault in remove component

### PR DESCRIPTION
**Pull request by kerimoyle**
Added test to demonstrate the behaviour described in #534

### CODE REVIEW

**Comment by kerimoyle** [comment]
Thanks @hsorby.  Should we be removing the equivalent variable connections when removing a component?  This is what was causing the segfault, not just the equivalent variable count.  Changing the test as in 3d84826 takes away the demonstration of that behaviour ...

**Comment by hsorby** [comment]
I only had the one segfault from the for loop on equivalent variable count.

**Comment by hsorby** [comment]
> Should we be removing the equivalent variable connections when removing a component?
No we shouldn't.

**Comment by kerimoyle** [comment]
> Should we be removing the equivalent variable connections when removing a component?
> No we shouldn't.

I don't understand.  Why does the equivalent variable count change when we remove a component if we're not changing the connections at all?  Isn't that what your test is showing? (I added the first four lines)

```
EXPECT_EQ(size_t(1), model->component(0)->variable(0)->equivalentVariableCount());
EXPECT_NE(nullptr, model->component(0)->variable(0)->equivalentVariable(0));

EXPECT_EQ(size_t(1), model->component(1)->variable(0)->equivalentVariableCount());
EXPECT_NE(nullptr, model->component(1)->variable(0)->equivalentVariable(0));

model->removeComponent("c1");

// I don't understand this line if the connection is supposed to remain? Shouldn't this stay at 1?
EXPECT_EQ(size_t(0), model->component(0)->variable(0)->equivalentVariableCount());
EXPECT_EQ(nullptr, model->component(0)->variable(0)->equivalentVariable(0));
```

**Comment by kerimoyle** [comment]
I've gone through the source code some more and I think that my confusion comes from the fact that we use "removeSomething" to mean "remove it AND delete what it pointed to", when I'd imagined that it simply removed the pointer from the list.  Since we don't create the object when calling the "addSomething" function, this is confusing!

The function names and documentation don't mention that the original object will be deleted, and it *really* limits the way that people can create and reuse objects through the API.  You couldn't have two models which used the same component or units, for example, because removing a set of units from one model would delete it, and cause problems in any other model which referenced them.  I'll try and make a test to show you what I mean.  

Would a clearer way be to have the `add/removeSomething` functions only adding/removing from the list of pointers in the object: **not** touching the contents of the pointers themselves.   We can then have a set of `deleteSomething` functions which could do both at once.  At least then the add/remove behaviour is more predictable, and allows the user to move things around as they want to without deleting them without realising it ...?

**Comment by hsorby** [comment]
I don't agree, if you don't retain a handle to an object that you are removing then it will be deleted.  This is pretty standard behaviour.

We also have the `take*` methods which gives the above behaviour.  The user must decide whether they want to remove something or take it.  Remove to me is doing what I would expect.

**Comment by kerimoyle** [comment]
Somewhere along the line the behaviour that was buggy has been fixed.  Not here, but somewhere ... so this PR doesn't really need to go in anymore unless we just want an extra test.

**Review by hsorby — APPROVED** [review]

**Review by nickerso — APPROVED** [review]

**Pull request merged**
