### PR TITLE
Flat models should have no import sources

### LINKED ISSUE #702: Importer: Flattened models should not contain any importSource items
I've been able to break stuff by assuming that flat models have `model->importSourceCount() == 0` ... which isn't true in a few of our test cases.  It really should be zero, so we need to check where this is coming from ...

### PR DESCRIPTION
**Pull request by kerimoyle**
Closes #702 

This PR cleans up the two-way connection between imported items and their import sources so that flattened models don't have any `importSource` items.

### CODE REVIEW

**Comment by kerimoyle** [comment]
Ready for review please @agarny @hsorby @nickerso This is a small one so should be pretty straightforward.  I need this to be merged so I can keep working on the examples for COMBINE...

**Review by agarny — COMMENTED** [review]
Looks fine, but how come there is/are no new test/s?

**Comment by kerimoyle** [comment]
Ah, good point.  I found the bug writing the tutorials - I'll write a quick test for it now.

**Comment by kerimoyle** [comment]
@agarny Should be clearer now? I've just added a few lines that failed prior to this fix.

**Review by agarny — APPROVED** [review]

**Comment by agarny** [comment]
> @agarny Should be clearer now? I've just added a few lines that failed prior to this fix.

Yup, happy with that. Thanks.

**Review by hsorby — APPROVED** [review]

**Pull request merged**
