### PR TITLE
Remove ability for Component class to hold Units.

### PR DESCRIPTION
**Pull request by hsorby**
Addresses issue #154.

### CODE REVIEW

**Comment by hsorby** [comment]
This is ready for review.

**Review by nickerso — APPROVED** [review]
Looking good to me.

**Comment by nickerso** [comment]
@hsorby could you please give this a once over and make sure I haven't messed things up too bad while merging things and resolving conflicts. Otherwise I think its all good to merge now.

**Comment by hsorby** [comment]
@nickerso I think we are good now.

**Pull request merged**
