### PR TITLE
Added missing enums into __init__.py

### PR DESCRIPTION
**Pull request by kerimoyle**
Addresses #611

### CODE REVIEW

**Comment by kerimoyle** [comment]
Smallest PR ever ... assuming buildbot tests all pass, this is ready for review please @hsorby @agarny @nickerso

**Comment by agarny** [comment]
Considering the issue this PR fixes, doesn't it mean that we really ought to have a Python test for this (and, most likely, other aspects of our Python bindings)?

**Comment by kerimoyle** [comment]
I think there are probably a huge amount of missing Python tests!

**Comment by agarny** [comment]
I know. I just thought I would raise the issue. In fact, we probably ought to have a proper issue for this. As for this PR, I am just waiting for the tests to pass and will then approve it.

**Comment by kerimoyle** [comment]
Yep, good idea.  I'll make one now ...

**Review by agarny — DISMISSED** [review]

**Review by agarny — APPROVED** [review]

**Review by nickerso — APPROVED** [review]

**Pull request merged**
