### PR TITLE
Tests: treat warnings as errors (#239)

### PR DESCRIPTION
**Pull request by agarny**
This addresses issue #239.

### CODE REVIEW

**Comment by agarny** [comment]
Ping @hsorby since I still can't add you as a reviewer...

**Comment by MichaelClerx** [comment]
Closes #239

**Review by MichaelClerx — APPROVED** [review]
Could we have all the refactoring in separate PRs next time :D 

Happy to merge this if @hsorby has no objections.

**Comment by agarny** [comment]
> Could we have all the refactoring in separate PRs next time :D

Yes, I wasn't quite sure how to handle them since they were all triggered as a result of issue #239 (apart from the trailing spaces commit). So, it felt easier to have one "big" PR rather than several small ones as a prerequisite to this one.

**Comment by MichaelClerx** [comment]
Cool!

**Comment by nickerso** [comment]
Best to let @hsorby check this one before merging...or at least someone who understands C++ a lot better than me :)

**Comment by hsorby** [comment]
I have no problem with this.  And all the tests pass so the gtest error is no longer present.

**Pull request merged**
