### PR TITLE
Updated parser test to include alternative error messages from Ubuntu 20

### LINKED ISSUE #751: Failing `io_unit_test_parser` test
```
99% tests passed, 1 tests failed out of 67

Total Test time (real) =  18.64 sec

The following tests FAILED:
	 15 - io_unit_test_parser (Failed)
Errors while running CTest
make: *** [Makefile:172: test] Error 8
```

### PR DESCRIPTION
**Pull request by kerimoyle**
Closes #751

### CODE REVIEW

**Comment by kerimoyle** [comment]
@agarny Please can you confirm that this fixes the problem on the Ubuntu 20 build?

**Comment by agarny** [comment]
> @agarny Please can you confirm that this fixes the problem on the Ubuntu 20 build?

I can confirm that everything is now fine on Ubuntu 20.04.

**Comment by kerimoyle** [comment]
Ready for review please @agarny @nickerso @hsorby

**Review by agarny — DISMISSED** [review]

**Review by hsorby — DISMISSED** [review]
I think I would have had the `expectedIssues*` named after the libxml2 version rather than Ubuntu version as this is the source of the difference but I can live with the current names.

**Comment by agarny** [comment]
> I think I would have had the `expectedIssues*` named after the libxml2 version rather than Ubuntu version as this is the source of the difference but I can live with the current names.

I actually had the same thought, so maybe it should be done? I mean, who knows when we will next look into this, so we might as well have the correct information in?

**Review by agarny — APPROVED** [review]

**Review by hsorby — APPROVED** [review]

**Pull request merged**
